#!/usr/bin/env python3
"""
simulate_stream.py — append a fake agent conversation to a project, slowly,
so the GUI's real-time view can be demonstrated without the agent CLIs.

It writes in the EXACT format orchestrator.py uses (same Markdown blocks, same
agent_state.json fields, same transient .lock), so the SwiftUI app shows live
bubbles appearing, the "thinking" indicator, a coordinator decision, the phase
turning green, and the next phase going active — just as a real run would.

Stdlib only.

Usage:
  python3 .orchestrator/simulate_stream.py --app taskquill
  python3 .orchestrator/simulate_stream.py --app taskquill --delay 2.0
"""

import argparse
import datetime as _dt
import json
import os
import time

HERE = os.path.dirname(os.path.abspath(__file__))


def lock_path(app):
    """Demo-specific, per-app lock name: two concurrent `--app` demo runs must
    not delete each other's lock in the finally-block cleanup, and this dev
    tool's lock must never collide with a real run's lock file in the engine
    dir either."""
    return os.path.join(HERE, ".simulate_stream.%s.lock" % app)


# Default workspace: ORCH_ROOT env, else <repo>/workspace next to this engine dir.
ROOT_DEFAULT = os.environ.get("ORCH_ROOT") or os.path.join(os.path.dirname(HERE), "workspace")

PHASES = [
    ("initial_discussion", "initial_discussion", "initial_discussion.md", "Initial Discussion"),
    ("next_steps_small", "next_steps_small", "next_steps_small.md", "Next Steps Small"),
    ("detailed_discussion", "detailed_discussion", "detailed_discussion.md", "Detailed Discussion"),
    ("app_features", "app_features", "app_features.md", "App Features"),
    ("design_discussion", "design_discussion", "design_discussion.md", "Design Discussion"),
    ("tech_specs", "tech_specs", "tech_specs.md", "Tech Specs"),
    ("project_plan", "project_plan", "project_plan.md", "Project Plan"),
    ("task_assignments", "task_assignments", "task_assignments.md", "Task Assignments"),
    ("build_coordination", "build_coordination", "agent_messages.md", "Build Coordination"),
    ("final_review", "final_review", "final_review.md", "Final Review"),
]
DISPLAY = {"codex": "Codex", "claude": "Claude", "gemini": "Gemini"}
SIGNATURE = {"codex": "From Codex", "claude": "From Claude", "gemini": "From Gemini"}
ORDER = ["codex", "claude", "gemini"]
SAY = {
    "codex": "Pragmatic take: ship the minimal slice; my proposal scores 85/100. "
             "Claude's extra guard is out of scope for v1.",
    "claude": "Correctness concern: the crash-recovery path is unhandled. I score "
              "the safe variant 88/100 and push to include it now.",
    "gemini": "Simplicity wins: fewer moving parts for the user. I side with the "
              "atomic-write approach at 86/100 and drop the heavier option.",
}


def now_str():
    return _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def touch_lock(path):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("pid=%d host=simulate started=%s\n" % (os.getpid(), now_str()))


def append(path, text):
    with open(path, "a", encoding="utf-8") as fh:
        fh.write(text)


def header(app, title):
    return (
        "# %s — %s\n\n" % (app, title)
        + "_Generated by the autonomous multi-agent orchestrator on %s._\n\n" % now_str()
        + "## Original Prompt\n\n```\n(streamed demo)\n```\n\n"
        + "## Phase Purpose\n\nDemo of the live transcript stream.\n\n"
        + "## Rubric\n\nThe agents agree a 100-point rubric in the transcript.\n\n"
        + "## Transcript\n\n"
    )


def load_state(app_dir):
    p = os.path.join(app_dir, "agent_state.json")
    if os.path.exists(p):
        try:
            with open(p, encoding="utf-8") as fh:
                return json.load(fh)
        except (OSError, ValueError):
            pass   # corrupt/unreadable state -> fall through to a fresh demo state
    return {
        "current_phase": None, "current_round": 0, "next_agent": None,
        "prompt_hash": "demo", "completed_phases": [], "phase_outputs": {},
        "last_processed": None, "consensus_status": {}, "vote_results": {},
        "done": False, "error": None,
    }


def save_state(app_dir, state):
    state["last_processed"] = now_str()
    tmp = os.path.join(app_dir, "agent_state.json.tmp")
    with open(tmp, "w", encoding="utf-8") as fh:
        json.dump(state, fh, indent=2)
    os.replace(tmp, os.path.join(app_dir, "agent_state.json"))


PERSONAS = {"codex": "Pragmatist", "claude": "Skeptic", "gemini": "Visionary"}
CHAT_SAY = {
    "codex": "Concretely: a menu-bar water-intake tracker is a weekend build — "
             "one window, one HealthKit write, no accounts.",
    "claude": "Push back gently: intake trackers are crowded. The wedge is the "
              "REMINDER quality — tie prompts to calendar gaps, not timers.",
    "gemini": "Building on both: ship the tracker skeleton, but make the "
              "calendar-aware nudge the hero feature of the store listing.",
}


def run_conversational(args):
    """V3 board 1.6: demo a CONVERSATIONAL session with no CLIs — mints the
    flat chat dir (initial_prompt + workflow.txt=chat_ideas, the engine/GUI
    discovery contract), writes chat/chat.md in the exact conversational
    format (human blocks, persona hats, a Local (Ollama) turn, NO
    coordinator), and flips next_agent ('+'-joined roster) / awaiting_human
    in agent_state.json so the surface shows replying + waiting states."""
    app_dir = os.path.join(args.root, args.app)
    prompt_dir = os.path.join(app_dir, "initial_prompt")
    os.makedirs(prompt_dir, exist_ok=True)
    seed_p = os.path.join(prompt_dir, "initial_prompt.md")
    if not os.path.exists(seed_p):
        with open(seed_p, "w", encoding="utf-8") as fh:
            fh.write("Brainstorm a weekend-sized iOS utility.\n")
    with open(os.path.join(app_dir, "workflow.txt"), "w", encoding="utf-8") as fh:
        fh.write("chat_ideas\n")

    phase_dir = os.path.join(app_dir, "chat")
    os.makedirs(phase_dir, exist_ok=True)
    md = os.path.join(phase_dir, "chat.md")
    if not os.path.exists(md):
        append(md, header(args.app, "Ideas Chat"))

    state = load_state(app_dir)
    lock = lock_path(args.app)
    touch_lock(lock)
    roster = ["codex", "claude", "gemini"]
    human_msgs = ["What's a tiny iOS utility I could ship this weekend?",
                  "Which of those survives App Review most easily?"]
    try:
        for rnd, human in enumerate(human_msgs, start=1):
            state["current_phase"] = "chat"
            state["current_round"] = rnd
            state["awaiting_human"] = None
            state["next_agent"] = "+".join(roster)
            save_state(app_dir, state)
            append(md, "\n### Round %d\n\n" % rnd)
            append(md, "\n**You (human) — Round %d**\n\n%s\n" % (rnd, human))
            print("  Round %d: human message posted; panel replying…" % rnd)
            time.sleep(args.delay)
            for agent in roster:
                block = "**%s (%s) — Round %d**\n\n%s\n\n%s\n" % (
                    DISPLAY[agent], PERSONAS[agent], rnd, CHAT_SAY[agent],
                    SIGNATURE[agent])
                append(md, "\n" + block)
            # One local-model turn: the header the parser must not swallow.
            append(md, "\n**Local (Ollama) — Round %d**\n\nCheap second "
                       "opinion: both ideas fit in a weekend; the reminder "
                       "angle differentiates.\n" % rnd)
            # Panel done -> the engine would now block in _await_inbox.
            state["next_agent"] = None
            state["awaiting_human"] = "chat"
            save_state(app_dir, state)
            print("  Round %d complete — waiting for you…" % rnd)
            time.sleep(args.delay * 2)

        closure = ("Conversation closed after %d round(s): ended by user. The "
                   "transcript above is the record of this chat." % len(human_msgs))
        append(md, "\n## Coordinator Decision\n\n_No coordinator — "
                   "conversational phase; ended by user._\n")
        append(md, "\n## Final Output\n\n%s\n" % closure)
        append(md, "\n---\n\nENDED BY USER\n")
        state["awaiting_human"] = None
        state["next_agent"] = None
        state["current_round"] = 0
        state.setdefault("completed_phases", []).append("chat")
        state["phase_outputs"]["chat"] = closure
        state["consensus_status"]["chat"] = False
        state.setdefault("conversation_end", {})["chat"] = "ended by user"
        state["done"] = True
        save_state(app_dir, state)
        print("Conversation ended (ENDED BY USER); state done.")
    finally:
        if os.path.exists(lock):
            try:
                os.remove(lock)
            except OSError:
                pass


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--app", required=True)
    ap.add_argument("--root", default=ROOT_DEFAULT)
    ap.add_argument("--delay", type=float, default=2.5)
    ap.add_argument("--conversational", action="store_true",
                    help="demo a chat session (mints the dir; no CLIs needed)")
    args = ap.parse_args()

    if args.conversational:
        run_conversational(args)
        return

    app_dir = os.path.join(args.root, args.app)
    if not os.path.isdir(app_dir):
        raise SystemExit("No such project: %s" % app_dir)
    lock = lock_path(args.app)

    state = load_state(app_dir)
    # Choose the phase to stream into: current, else first incomplete, else first.
    key = state.get("current_phase")
    if not key or key in state.get("completed_phases", []):
        key = next((k for (k, *_r) in PHASES if k not in state.get("completed_phases", [])),
                   PHASES[0][0])
    pdef = next(p for p in PHASES if p[0] == key)
    _key, folder, fname, title = pdef
    phase_dir = os.path.join(app_dir, folder)
    os.makedirs(phase_dir, exist_ok=True)
    md = os.path.join(phase_dir, fname)
    if not os.path.exists(md):
        append(md, header(args.app, title))

    rnd = int(state.get("current_round", 0)) + 1
    print("Streaming %s / %s round %d (delay %.1fs)" % (args.app, key, rnd, args.delay))

    state["current_phase"] = key
    state["current_round"] = rnd
    save_state(app_dir, state)
    touch_lock(lock)
    append(md, "\n### Round %d\n\n" % rnd)

    try:
        for agent in ORDER:
            state["next_agent"] = agent
            save_state(app_dir, state)
            touch_lock(lock)
            print("  %s is thinking…" % DISPLAY[agent])
            time.sleep(args.delay)
            block = "**%s — Round %d**\n\n%s\n\n%s\n" % (
                DISPLAY[agent], rnd, SAY[agent], SIGNATURE[agent])
            append(md, "\n" + block)
            print("  %s responded." % DISPLAY[agent])

        # Coordinator declares consensus and completes the phase.
        state["next_agent"] = "gemini"
        save_state(app_dir, state)
        touch_lock(lock)
        time.sleep(args.delay)
        final = ("Decision: adopt the safe atomic-write approach with a recovery "
                 "path. Owners and thresholds fixed; feeds the next phase.")
        cresp = ("As coordinator I find genuine consensus.\n\nCONSENSUS: YES\n\n"
                 "## Final Output\n\n%s\n\n%s" % (final, SIGNATURE["gemini"]))
        append(md, "\n**Coordinator (Gemini) — decision after round %d**\n\n%s\n" % (rnd, cresp))
        append(md, "\n## Coordinator Decision\n\nSee the coordinator's message above.\n")
        append(md, "\n## Final Output\n\n%s\n" % final)
        append(md, "\n---\n\nCONSENSUS: YES\n")
        print("  Coordinator reached consensus.")

        # Mark phase complete and advance.
        if key not in state["completed_phases"]:
            state["completed_phases"].append(key)
        state["phase_outputs"][key] = final
        state["consensus_status"][key] = True
        nxt = next((k for (k, *_r) in PHASES if k not in state["completed_phases"]), None)
        state["current_phase"] = nxt
        state["current_round"] = 0
        state["next_agent"] = None
        if nxt is None:
            state["done"] = True
        save_state(app_dir, state)
        print("Phase '%s' complete. Next: %s" % (key, nxt or "(all done)"))
    finally:
        if os.path.exists(lock):
            try:
                os.remove(lock)
            except OSError:
                pass


if __name__ == "__main__":
    main()
