#!/usr/bin/env python3
"""
simulate_stream.py — append a fake agent conversation to a project, slowly,
so the GUI's real-time view can be demonstrated without the agent CLIs.

It writes in the EXACT format orchestrator.py uses (same Markdown blocks, same
agent_state.json fields, same transient .lock), so the SwiftUI app shows live
bubbles appearing, the "thinking" indicator, a coordinator decision, the phase
turning green, and the next phase going active — just as a real run would.

Stdlib only.

Usage:
  python3 .orchestrator/simulate_stream.py --app taskquill
  python3 .orchestrator/simulate_stream.py --app taskquill --delay 2.0
"""

import argparse
import datetime as _dt
import json
import os
import time

HERE = os.path.dirname(os.path.abspath(__file__))
LOCK_PATH = os.path.join(HERE, ".lock")
# Default workspace: ORCH_ROOT env, else <repo>/workspace next to this engine dir.
ROOT_DEFAULT = os.environ.get("ORCH_ROOT") or os.path.join(os.path.dirname(HERE), "workspace")

PHASES = [
    ("initial_discussion", "initial_discussion", "initial_discussion.md", "Initial Discussion"),
    ("next_steps_small", "next_steps_small", "next_steps_small.md", "Next Steps Small"),
    ("detailed_discussion", "detailed_discussion", "detailed_discussion.md", "Detailed Discussion"),
    ("app_features", "app_features", "app_features.md", "App Features"),
    ("design_discussion", "design_discussion", "design_discussion.md", "Design Discussion"),
    ("tech_specs", "tech_specs", "tech_specs.md", "Tech Specs"),
    ("project_plan", "project_plan", "project_plan.md", "Project Plan"),
    ("task_assignments", "task_assignments", "task_assignments.md", "Task Assignments"),
    ("build_coordination", "build_coordination", "agent_messages.md", "Build Coordination"),
    ("final_review", "final_review", "final_review.md", "Final Review"),
]
DISPLAY = {"codex": "Codex", "claude": "Claude", "gemini": "Gemini"}
SIGNATURE = {"codex": "From Codex", "claude": "From Claude", "gemini": "From Gemini"}
ORDER = ["codex", "claude", "gemini"]
SAY = {
    "codex": "Pragmatic take: ship the minimal slice; my proposal scores 85/100. "
             "Claude's extra guard is out of scope for v1.",
    "claude": "Correctness concern: the crash-recovery path is unhandled. I score "
              "the safe variant 88/100 and push to include it now.",
    "gemini": "Simplicity wins: fewer moving parts for the user. I side with the "
              "atomic-write approach at 86/100 and drop the heavier option.",
}


def now_str():
    return _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def touch_lock():
    with open(LOCK_PATH, "w", encoding="utf-8") as fh:
        fh.write("pid=%d host=simulate started=%s\n" % (os.getpid(), now_str()))


def append(path, text):
    with open(path, "a", encoding="utf-8") as fh:
        fh.write(text)


def header(app, title):
    return (
        "# %s — %s\n\n" % (app, title)
        + "_Generated by the autonomous multi-agent orchestrator on %s._\n\n" % now_str()
        + "## Original Prompt\n\n```\n(streamed demo)\n```\n\n"
        + "## Phase Purpose\n\nDemo of the live transcript stream.\n\n"
        + "## Rubric\n\nThe agents agree a 100-point rubric in the transcript.\n\n"
        + "## Transcript\n\n"
    )


def load_state(app_dir):
    p = os.path.join(app_dir, "agent_state.json")
    if os.path.exists(p):
        with open(p, encoding="utf-8") as fh:
            return json.load(fh)
    return {
        "current_phase": None, "current_round": 0, "next_agent": None,
        "prompt_hash": "demo", "completed_phases": [], "phase_outputs": {},
        "last_processed": None, "consensus_status": {}, "vote_results": {},
        "done": False, "error": None,
    }


def save_state(app_dir, state):
    state["last_processed"] = now_str()
    tmp = os.path.join(app_dir, "agent_state.json.tmp")
    with open(tmp, "w", encoding="utf-8") as fh:
        json.dump(state, fh, indent=2)
    os.replace(tmp, os.path.join(app_dir, "agent_state.json"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--app", required=True)
    ap.add_argument("--root", default=ROOT_DEFAULT)
    ap.add_argument("--delay", type=float, default=2.5)
    args = ap.parse_args()

    app_dir = os.path.join(args.root, args.app)
    if not os.path.isdir(app_dir):
        raise SystemExit("No such project: %s" % app_dir)

    state = load_state(app_dir)
    # Choose the phase to stream into: current, else first incomplete, else first.
    key = state.get("current_phase")
    if not key or key in state.get("completed_phases", []):
        key = next((k for (k, *_r) in PHASES if k not in state.get("completed_phases", [])),
                   PHASES[0][0])
    pdef = next(p for p in PHASES if p[0] == key)
    _key, folder, fname, title = pdef
    phase_dir = os.path.join(app_dir, folder)
    os.makedirs(phase_dir, exist_ok=True)
    md = os.path.join(phase_dir, fname)
    if not os.path.exists(md):
        append(md, header(args.app, title))

    rnd = int(state.get("current_round", 0)) + 1
    print("Streaming %s / %s round %d (delay %.1fs)" % (args.app, key, rnd, args.delay))

    state["current_phase"] = key
    state["current_round"] = rnd
    save_state(app_dir, state)
    touch_lock()
    append(md, "\n### Round %d\n\n" % rnd)

    try:
        for agent in ORDER:
            state["next_agent"] = agent
            save_state(app_dir, state)
            touch_lock()
            print("  %s is thinking…" % DISPLAY[agent])
            time.sleep(args.delay)
            block = "**%s — Round %d**\n\n%s\n\n%s\n" % (
                DISPLAY[agent], rnd, SAY[agent], SIGNATURE[agent])
            append(md, "\n" + block)
            print("  %s responded." % DISPLAY[agent])

        # Coordinator declares consensus and completes the phase.
        state["next_agent"] = "gemini"
        save_state(app_dir, state)
        touch_lock()
        time.sleep(args.delay)
        final = ("Decision: adopt the safe atomic-write approach with a recovery "
                 "path. Owners and thresholds fixed; feeds the next phase.")
        cresp = ("As coordinator I find genuine consensus.\n\nCONSENSUS: YES\n\n"
                 "## Final Output\n\n%s\n\n%s" % (final, SIGNATURE["gemini"]))
        append(md, "\n**Coordinator (Gemini) — decision after round %d**\n\n%s\n" % (rnd, cresp))
        append(md, "\n## Coordinator Decision\n\nSee the coordinator's message above.\n")
        append(md, "\n## Final Output\n\n%s\n" % final)
        append(md, "\n---\n\nCONSENSUS: YES\n")
        print("  Coordinator reached consensus.")

        # Mark phase complete and advance.
        if key not in state["completed_phases"]:
            state["completed_phases"].append(key)
        state["phase_outputs"][key] = final
        state["consensus_status"][key] = True
        nxt = next((k for (k, *_r) in PHASES if k not in state["completed_phases"]), None)
        state["current_phase"] = nxt
        state["current_round"] = 0
        state["next_agent"] = None
        if nxt is None:
            state["done"] = True
        save_state(app_dir, state)
        print("Phase '%s' complete. Next: %s" % (key, nxt or "(all done)"))
    finally:
        if os.path.exists(LOCK_PATH):
            try:
                os.remove(LOCK_PATH)
            except OSError:
                pass


if __name__ == "__main__":
    main()
