"""V3 board 2.1: the golden transcript suite — the byte-compatibility keel.

Five representative transcript shapes are generated with fully deterministic
stubs and compared BYTE-FOR-BYTE against committed fixtures (the one
timestamp line the header carries is masked — it is the only
non-deterministic byte source in a phase .md). These fixtures are the
contract the M2 refactors (2.2 process_phase extraction, 2.3 TurnContext,
2.4 dual-write) must keep green after EVERY sub-PR: crash resume and the
GUI's TranscriptParser both regex-parse this exact format.

Regenerate deliberately, never accidentally:
    ORCH_GOLDEN_REGEN=1 python3 -m unittest tests.test_transcript_golden
then eyeball `git diff tests/golden_transcripts/` before committing.
"""
import os
import re
import tempfile
import unittest

import orchestrator as orch
import workflows as wf

GOLDEN_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                          "golden_transcripts")
REGEN = os.environ.get("ORCH_GOLDEN_REGEN") == "1"

# The single non-deterministic line a phase .md contains.
_TS_RE = re.compile(
    r"_Generated by the autonomous multi-agent orchestrator on [^_]+_")


def _normalize(text):
    return _TS_RE.sub(
        "_Generated by the autonomous multi-agent orchestrator on <TS>._", text)


def _write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


class GoldenBase(unittest.TestCase):
    maxDiff = None   # byte diffs must be fully visible when they happen

    def setUp(self):
        self.app_dir = tempfile.mkdtemp()
        self._orig = {
            "sessioned": orch.call_agent_sessioned,
            "call": orch.call_agent,
            "avail": orch._agent_available,
        }

    def tearDown(self):
        orch.call_agent_sessioned = self._orig["sessioned"]
        orch.call_agent = self._orig["call"]
        orch._agent_available = self._orig["avail"]

    def _cfg(self, agents=("codex",), **runtime_over):
        runtime = {"parallel_discussion_rounds": False,
                   "phase_quality_gates_enabled": False,
                   "phase_independent_first_round_enabled": False,
                   "approval_timeout_seconds": 30}
        runtime.update(runtime_over)
        return {"agents": {"codex_enabled": "codex" in agents,
                           "claude_enabled": "claude" in agents,
                           "gemini_enabled": "gemini" in agents},
                "runtime": runtime,
                "_workflow_target": "app", "_app_dir": self.app_dir,
                "root": self.app_dir}

    def _state(self, **over):
        st = {"current_phase": None, "current_round": 0,
              "completed_phases": [], "phase_outputs": {},
              "consensus_status": {}, "vote_results": {}, "prompt_hash": "h"}
        st.update(over)
        return st

    def _md(self, fname="d.md"):
        with open(os.path.join(self.app_dir, fname), encoding="utf-8") as fh:
            return fh.read()

    def assert_golden(self, name, text):
        path = os.path.join(GOLDEN_DIR, name + ".md")
        norm = _normalize(text)
        if REGEN:
            _write(path, norm)
            self.skipTest("regenerated %s" % name)
        self.assertTrue(os.path.exists(path),
                        "missing fixture %s — run with ORCH_GOLDEN_REGEN=1" % name)
        with open(path, encoding="utf-8") as fh:
            expected = fh.read()
        self.assertEqual(norm, expected,
                         "TRANSCRIPT BYTES DRIFTED (%s) — crash resume and the "
                         "GUI parser depend on this exact format. If the change "
                         "is deliberate, regenerate the fixture and say why in "
                         "the commit." % name)


class TestGoldenTranscripts(GoldenBase):
    def test_debate_consensus(self):
        # Two rounds; consensus lands at round 2's coordinator turn.
        def sessioned(cfg, app, phase, rnd, agent, prompt,
                      delta_prompt=None, session_key=None):
            if (session_key or "").endswith(":coord"):
                if rnd >= 2:
                    return ("We converge on the resilient option.\n\n"
                            "CONSENSUS: YES\n\n## Final Output\n\n"
                            "Ship the resilient option with a rollback plan.\n")
                return "Not yet — sharpen the tradeoff. CONSENSUS: NO"
            return "Round %d take: prefer the resilient option." % rnd
        orch.call_agent_sessioned = sessioned
        orch._agent_available = lambda a, cfg=None: a == "codex"
        orch.process_phase(self._cfg(), "golden", self.app_dir,
                           wf.Phase("design_discussion", ".", "d.md", "decide",
                                    rounds=3),
                           "golden prompt", [("earlier", "prior decision")],
                           self._state())
        self.assert_golden("debate_consensus", self._md())

    def test_debate_with_pass(self):
        # Round 2 is an honest abstention (the PASS protocol's one-line slip).
        def sessioned(cfg, app, phase, rnd, agent, prompt,
                      delta_prompt=None, session_key=None):
            if (session_key or "").endswith(":coord"):
                if rnd >= 2:
                    return ("Everyone passed — converged.\n\nCONSENSUS: YES\n\n"
                            "## Final Output\n\nAdopt round 1's position.\n")
                return "Continue. CONSENSUS: NO"
            return "PASS" if rnd == 2 else "Initial position, round %d." % rnd
        orch.call_agent_sessioned = sessioned
        orch._agent_available = lambda a, cfg=None: a == "codex"
        orch.process_phase(self._cfg(), "golden", self.app_dir,
                           wf.Phase("design_discussion", ".", "d.md", "decide",
                                    rounds=3),
                           "golden prompt", [], self._state())
        self.assert_golden("debate_pass", self._md())

    def test_forced_vote_deterministic_tally(self):
        # Two agents, no consensus by max rounds -> concurrent ballots,
        # deterministic confidence-weighted tally, VOTE_DECISION footer.
        def sessioned(cfg, app, phase, rnd, agent, prompt,
                      delta_prompt=None, session_key=None):
            if (session_key or "").endswith(":coord"):
                return "Still split. CONSENSUS: NO"
            return "%s position, round %d." % (agent, rnd)

        def vote_call(cfg, app, phase, rnd, agent, prompt):
            other = "claude" if agent == "codex" else "codex"
            return ("My ballot:\n```vote-json\n"
                    '{"choice": "%s", "confidence": 4, '
                    '"reason": "their proposal is more complete"}\n```' % other)
        orch.call_agent_sessioned = sessioned
        orch.call_agent = vote_call
        orch._agent_available = lambda a, cfg=None: a in ("codex", "claude")
        orch.process_phase(self._cfg(agents=("codex", "claude")), "golden",
                           self.app_dir,
                           wf.Phase("design_discussion", ".", "d.md", "decide",
                                    rounds=1),
                           "golden prompt", [], self._state())
        self.assert_golden("forced_vote", self._md())

    def test_resume_mid_round_appends_only(self):
        # A crashed round-2 debate resumes: round 1 bytes untouched, round 2
        # redone, consensus at round 2.
        existing = ("# golden — Design Discussion\n\n## Transcript\n\n"
                    "\n### Round 1\n\n"
                    "**Codex (Product Strategist · Visionary) — Round 1**\n\n"
                    "pre-crash position\n"
                    "\n**Coordinator (Codex) — decision after round 1**\n\n"
                    "Continue. CONSENSUS: NO\n")
        _write(os.path.join(self.app_dir, "d.md"), existing)

        def sessioned(cfg, app, phase, rnd, agent, prompt,
                      delta_prompt=None, session_key=None):
            if (session_key or "").endswith(":coord"):
                return ("Converged after resume.\n\nCONSENSUS: YES\n\n"
                        "## Final Output\n\nKeep the pre-crash direction.\n")
            return "post-resume position, round %d." % rnd
        orch.call_agent_sessioned = sessioned
        orch._agent_available = lambda a, cfg=None: a == "codex"
        orch.process_phase(self._cfg(), "golden", self.app_dir,
                           wf.Phase("design_discussion", ".", "d.md", "decide",
                                    rounds=3),
                           "golden prompt", [],
                           self._state(current_phase="design_discussion",
                                       current_round=2))
        text = self._md()
        self.assertIn("pre-crash position", text)   # append-only, sanity
        self.assert_golden("resume_mid_round", text)

    def test_conversational(self):
        # One human round then an explicit end — the 1.1 format: human block,
        # no coordinator bubble, honest footer, ENDED BY USER marker.
        _write(os.path.join(self.app_dir, "human_inbox.txt"),
               "hello panel, one idea each please")

        def sessioned(cfg, app, phase, rnd, agent, prompt,
                      delta_prompt=None, session_key=None):
            _write(os.path.join(self.app_dir, "approvals", "chat.ok"), "")
            return "One idea: a tide-clock widget."
        orch.call_agent_sessioned = sessioned
        orch._agent_available = lambda a, cfg=None: a == "codex"
        orch.process_phase(self._cfg(), "golden", self.app_dir,
                           wf.Phase("chat", ".", "chat.md", "talk", rounds=0,
                                    conversational=True),
                           "golden prompt", [], self._state())
        self.assert_golden("conversational", self._md("chat.md"))


if __name__ == "__main__":
    unittest.main()
